//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public int OperationID { get; set; }
        public string InID { get; set; }
        public string OutID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime OperationTime { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Card Card1 { get; set; }
    }
}
